### ISSUE TITLE
New socket file location

### ISSUE THREAD

**Issue by thefinn93** [inthewaves/kotlin-signald#17]
Hello,
This is to let you know that signald is moving it's default socket file location. The old location and the new location should both be searched, as the old location isn't being deprecated any time soon.

more details in [#66](https://gitlab.com/signald/signald/-/issues/66), although what you need to know is:

>please ensure your client's default behavior when the user has not specified a different path to the socket file is to first attempt to connect to `$XDG_RUNTIME_DIR/signald/signald.sock`, then fall back to `/var/run/signald/signald.sock`.

signald has a CLI flag `--user-socket` to it to make it use the new behavior.

**Comment by inthewaves** [comment]
Thanks for the heads up!

`$XDG_RUNTIME_DIR/signald/signald.sock` is already included in the default socket paths to try:

https://github.com/inthewaves/kotlin-signald/blob/68635cfc75e435a343b45278def38b3c4cb8a790/client/src/commonMain/kotlin/org/inthewaves/kotlinsignald/Sockets.kt#L34-L38

**Comment by thefinn93** [comment]
awesome, i probably should have checked first. Most of the implementations didnt have it so i just filed issues on everyone.
